const madhyaPradesh = [
    "Agar",
    "Ahirkhedi",
    "Ajaigarh",
    "Akoda",
    "Akodia",
    "Alampur",
    "Alirajpur",
    "Bhopal",
    "Gogaon",
    "Gogapur (Mehidpur Road)",
    "Gohad",
    "Goraiya",
    "Gormi",
    "Gotegaon (Chhota Chhindwara)",
    "Govindgarh",
    "Gujarkheda",
    "Guna",
    "Lahar",
    "Lakhnadon",
    "Lanji",
    "Lasudiya Mori",
    "Lateri",
    "Laundi (Lavkushnagar)",
    "Lidhora Khas",
    "Limbodi",
    "Lodhikheda",
    "Manegaon",
    "Mangawan",
    "Manglaya Sadak",
    "Manpur",
    "Mau",
    "Mauganj",
    "Meghnagar",
    "Meharagaon",
    "Mehgaon",
    "Pichhore",
    "Pindrai",
    "Pipalrawan",
    "Pipariya",
    "Pipariya",
    "Piplanarayanwar",
    "Piploda",
    "Piplya Kumar",
    "Piplya Mandi",
    "Pipri",
    "Sheopur",
    "Shivpuri",
    "Shujalpur",
    "Sidhi",
    "Sihora",
    "Silwani",
    "Singoli",
    "Singrauli",
    "Sinhasa",
    "Gwalior"
];

const andhraPradesh = [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Kakinada",
    "Rajamahendravaram",
    "Kadapa",
    "Mangalagiri-Tadepalli",
    "Tirupati",
    "Anantapuram",
    "Ongole",
    "Vizianagaram",
    "Eluru",
    "Proddatur",
    "Nandyal",
    "Adoni",
    "Madanapalle",
    "Machilipatnam",
    "Tenali",
    "Chittoor",
    "Hindupur",
    "Srikakulam",
    "Bhimavaram",
    "Tadepalligudem",
    "Guntakal",
    "Dharmavaram",
    "Gudivada",
    "Narasaraopet",
    "Kadiri",
    "Tadipatri",
    "Chilakaluripet"
];

const arunachalPradesh = [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tawang",
    "Ziro",
    "Bomdila",
    "Aalo",
    "Tezu",
    "Khonsa",
    "Roing",
    "Daporijo",
    "Anini",
    "Seppa",
    "Changlang",
    "Namsai",
    "Yingkiong",
    "Koloriang",
    "Hawai",
    "Longding",
    "Miao",
    "Jairampur",
    "Dirang",
    "Deomali",
    "Basar",
    "Raga",
    "Palin",
    "Mechuka",
    "Tuting",
    "Geku",
    "Yupia"
];

const assam = [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Dhubri",
    "North Lakhimpur",
    "Karimganj",
    "Sivasagar",
    "Goalpara",
    "Barpeta",
    "Haflong",
    "Diphu",
    "Golaghat",
    "Hojai",
    "Mangaldai",
    "Nalbari",
    "Kokrajhar",
    "Morigaon",
    "Dhekiajuli",
    "Rangia",
    "Duliajan",
    "Digboi",
    "Margherita",
    "Lumding",
    "Badarpur",
    "Sarthebari"
];

const bihar = [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Bihar Sharif",
    "Ara",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chhapra",
    "Hajipur",
    "Dehri",
    "Bettiah",
    "Motihari",
    "Sasaram",
    "Saharsa",
    "Siwan",
    "Jamalpur",
    "Sitamarhi",
    "Nawada",
    "Bagaha",
    "Buxar",
    "Kishanganj",
    "Jehanabad",
    "Aurangabad",
    "Lakhisarai",
    "Narkatiaganj",
    "Jamui"
];

const chhattisgarh = [
    "Raipur",
    "Bhilai",
    "Korba",
    "Bilaspur",
    "Durg",
    "Raigarh",
    "Dhamtari",
    "Jagdalpur",
    "Ambikapur",
    "Bhatapara",
    "Mahasamund",
    "Champa",
    "Kumhari",
    "Kawardha",
    "Rajnandgaon",
    "Chirmiri",
    "Dalli-Rajhara",
    "Naila Janjgir",
    "Tilda Newra",
    "Manendragarh",
    "Sakti",
    "Mungeli",
    "Patan",
    "Dongargarh",
    "Khairagarh",
    "Bemetara",
    "Balod",
    "Baloda Bazar",
    "Gariaband",
    "Narayanpur"
];

const goa = [
    "Panaji",
    "Vasco da Gama",
    "Margao",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Canacona",
    "Cuncolim",
    "Curchorem",
    "Sanquelim",
    "Valpoi",
    "Quepem",
    "Sanguem",
    "Pernem",
    "Chicalim",
    "Chimbel",
    "Davorlim",
    "Navelim",
    "Sancoale",
    "Sanvordem"
];

const gujarat = [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Navsari",
    "Surendranagar",
    "Morbi",
    "Gandhidham",
    "Nadiad",
    "Bharuch",
    "Patan",
    "Porbandar",
    "Mehsana",
    "Bhuj",
    "Veraval",
    "Vapi",
    "Valsad",
    "Godhra",
    "Palanpur",
    "Himmatnagar",
    "Kalol",
    "Botad",
    "Amreli",
    "Gondal",
    "Jetpur",
    "Deesa"
];

const haryana = [
    "Faridabad",
    "Gurugram",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Sirsa",
    "Bhiwani",
    "Bahadurgarh",
    "Jind",
    "Thanesar",
    "Kaithal",
    "Rewari",
    "Palwal",
    "Hansi",
    "Narnaul"
];

const himachalPradesh = [
    "Shimla",
    "Dharamshala",
    "Solan",
    "Mandi",
    "Palampur",
    "Baddi",
    "Nahan",
    "Paonta Sahib",
    "Sundarnagar",
    "Chamba",
    "Una",
    "Kullu",
    "Hamirpur",
    "Bilaspur",
    "Yol Cantonment",
    "Nalagarh",
    "Nurpur",
    "Kangra",
    "Baijnath Paprola",
    "Santokhgarh",
    "Mehatpur Basdehra",
    "Shamshi",
    "Parwanoo",
    "Manali",
    "Tira Sujanpur",
    "Ghumarwin",
    "Dalhousie",
    "Rohru",
    "Nagrota Bagwan",
    "Rampur",
    "Jawalamukhi",
    "Jogindernagar",
    "Dera Gopipur",
    "Sarkaghat",
    "Jhakhri",
    "Indora",
    "Bhuntar",
    "Nadaun",
    "Theog",
    "Kasauli Cantonment",
    "Gagret",
    "Chuari Khas",
    "Daulatpur",
    "Sabathu Cantonment",
    "Dalhousie Cantonment",
    "Rajgarh",
    "Arki",
    "Dagshai Cantonment",
    "Seoni",
    "Talai",
    "Jutogh Cantonment",
    "Chaupal",
    "Rewalsar"
];

const jharkhand = [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar (Daltonganj)",
    "Phusro",
    "Chirkunda",
    "Jhumri Telaiya",
    "Chaibasa",
    "Sahibganj",
    "Gumia",
    "Madhupur",
    "Ghatshila",
    "Simdega",
    "Lohardaga",
    "Dumka",
    "Pakur",
    "Godda",
    "Chatra",
    "Gumla",
    "Latehar",
    "Khunti",
    "Koderma",
    "Jharia",
    "Adityapur",
    "Mango"
];

const karnatakaCities = [
    "Bangalore",
    "Mysore",
    "Hubli-Dharwad",
    "Mangalore",
    "Gulbarga",
    "Belgaum",
    "Bellary",
    "Shimoga",
    "Tumkur",
    "Bijapur",
    "Raichur",
    "Bidar",
    "Hospet",
    "Bhadravati",
    "Udupi",
    "Davangere",
    "Chitradurga",
    "Kolar",
    "Mandya",
    "Hassan",
    "Gadag",
    "Robertsonpet",
    "Haveri",
    "Bagalkot",
    "Karwar",
    "Ranebennur",
    "Ramanagaram",
    "Chikmagalur",
    "Gangavati",
    "Bagalkot",
    "Yadgir",
    "Sirsi",
    "Chintamani",
    "Sira",
    "Puttur",
    "Sakleshpur",
    "Dandeli",
    "Tiptur",
    "Madhugiri",
    "Mudhol",
    "Sindhnur",
    "Athni",
    "Gokak",
    "Kundapura",
    "Karkala",
    "Dharwad",
    "Chikkaballapur",
    "Channapatna",
    "Sidlaghatta",
    "Srinivaspur",
    "Mulbagal",
    "Malur",
    "Bangarapet",
    "Kolar Gold Fields",
    "Robertsonpet",
    "Koppal",
    "Hospet",
    "Gangavathi",
    "Yelburga",
    "Kushtagi",
    "Kanakagiri",
    "Mundargi",
    "Ron",
    "Nargund",
    "Lakshmeshwar",
    "Savanur",
    "Shiggaon",
    "Hangal",
    "Hirekerur",
    "Byadgi",
    "Rattihalli",
    "Shirahatti",
    "Honnali",
    "Harihar",
    "Jagalur",
    "Harapanahalli",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Gokak",
    "Kundapura",
    "Karkala",
    "Dharwad",
    "Chikkaballapur",
    "Channapatna",
    "Sidlaghatta",
    "Srinivaspur",
    "Mulbagal",
    "Malur",
    "Bangarapet",
    "Kolar Gold Fields",
    "Robertsonpet",
    "Koppal",
    "Gangavathi",
    "Yelburga",
    "Kushtagi",
    "Kanakagiri",
    "Mundargi",
    "Ron",
    "Nargund",
    "Lakshmeshwar",
    "Savanur",
    "Shiggaon",
    "Hangal",
    "Hirekerur",
    "Byadgi",
    "Rattihalli",
    "Shirahatti",
    "Honnali",
    "Harihar",
    "Jagalur",
    "Harapanahalli",
    "Kudligi",
    "Sandur",
    "Siruguppa",
    "Kampli",
    "Hadagalli",
    "Hagaribommanahalli",
    "Kottur"
];

const keralaCities = [
    "Thiruvananthapuram",
    "Kozhikode",
    "Kochi",
    "Kollam",
    "Thrissur",
    "Kannur",
    "Alappuzha",
    "Kottayam",
    "Palakkad",
    "Manjeri",
    "Thalassery",
    "Thrippunithura",
    "Ponnani",
    "Vatakara",
    "Kanhangad",
    "Payyanur",
    "Koyilandy",
    "Parappanangadi",
    "Kalamassery",
    "Kodungallur",
    "Neyyattinkara",
    "Tanur",
    "Kayamkulam",
    "Malappuram",
    "Guruvayur",
    "Thrikkakkara",
    "Irinjalakuda",
    "Wadakkancherry",
    "Nedumangad",
    "Kondotty",
    "Tirurangadi",
    "Tirur",
    "Panoor",
    "Kasaragod",
    "Feroke",
    "Kunnamkulam",
    "Ottappalam",
    "Thiruvalla",
    "Thodupuzha",
    "Perinthalmanna",
    "Karunagappalli",
    "Chalakudy",
    "Payyoli",
    "Koduvally",
    "Mananthavady",
    "Changanassery",
    "Mattanur",
    "Punalur",
    "Nilambur",
    "Cherthala",
    "Sultan Bathery",
    "Maradu",
    "Kottakkal",
    "Taliparamba",
    "Shornur",
    "Pandalam",
    "Kattappana",
    "Cherpulassery",
    "Mukkam",
    "Iritty",
    "Valanchery",
    "Varkala",
    "Nileshwaram",
    "Chavakkad",
    "Kothamangalam",
    "Pathanamthitta",
    "Attingal",
    "Paravur",
    "Ramanattukara",
    "Mannarkkad",
    "Erattupetta",
    "Sreekandapuram",
    "Angamaly",
    "Chittur-Thathamangalam",
    "Kalpetta",
    "North Paravur",
    "Haripad",
    "Muvattupuzha",
    "Kottarakara",
    "Kuthuparamba",
    "Adoor",
    "Pattambi",
    "Anthoor",
    "Perumbavoor",
    "Piravom",
    "Ettumanoor",
    "Mavelikkara",
    "Eloor",
    "Chengannur",
    "Vaikom",
    "Aluva",
    "Pala",
    "Koothattukulam"
];

const maharashtraCities = [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Pimpri-Chinchwad",
    "Nashik",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Aurangabad",
    "Navi Mumbai",
    "Solapur",
    "Mira-Bhayandar",
    "Jalgaon",
    "Dhule",
    "Amravati",
    "Nanded-Waghala",
    "Kolhapur",
    "Ulhasnagar",
    "Sangli",
    "Malegaon",
    "Akola",
    "Latur",
    "Bhiwandi-Nizampur",
    "Ahmednagar",
    "Chandrapur",
    "Parbhani",
    "Ichalkaranji",
    "Jalna",
    "Ambarnath",
    "Bhusawal",
    "Panvel",
    "Badlapur",
    "Beed",
    "Gondia",
    "Satara",
    "Barshi",
    "Yavatmal",
    "Achalpur",
    "Osmanabad",
    "Nandurbar",
    "Wardha",
    "Udgir",
    "Hinganghat"
];

const manipurCities = [
    "Imphal",
    "Churachandpur",
    "Thoubal",
    "Kakching",
    "Mayang Imphal",
    "Moirang",
    "Phek",
    "Yairipok",
    "Wangjing",
    "Bishnupur",
    "Jiribam",
    "Kamjong",
    "Pherzawl",
    "Chandel",
    "Tengnoupal",
    "Ukhrul",
    "Tamenglong",
    "Senapati",
    "Kangpokpi",
    "Noney"
];

const meghalayaCities = [
    "Shillong",
    "Tura",
    "Nongstoin",
    "Jowai",
    "Baghmara",
    "Williamnagar",
    "Resubelpara",
    "Nongpoh",
    "Mairang",
    "Sohra (Cherrapunji)",
    "Mawkyrwat",
    "Khliehriat",
    "Ampati",
    "Shella Bholaganj",
    "Mawphlang",
    "Pynursla",
    "Mawsmai"
];

const mizoramCities = [
    "Aizawl",
    "Lunglei",
    "Saiha",
    "Serchhip",
    "Champhai",
    "Kolasib",
    "Lawngtlai",
    "Mamit",
    "Thenzawl",
    "Sairang",
    "Darlawn",
    "North Vanlaiphai",
    "Khawhai",
    "Biate",
    "Vairengte",
    "Bairabi",
    "Hnahthial",
    "Saitual",
    "Khawzawl",
    "Tlabung",
    "Zawlnuam",
    "Lengpui",
    "North Kawnpui"
];

const nagalandCities = [
    "Dimapur",
    "Kohima",
    "Mokokchung",
    "Tuensang",
    "Mon",
    "Wokha",
    "Zunheboto",
    "Phek",
    "Kiphire",
    "Longleng",
    "Peren",
    "Chumoukedima",
    "Noklak",
    "Tseminyu",
    "Shamator",
    "Niuland"
];

const odishaCities = [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Brahmapur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Jharsuguda",
    "Jeypore",
    "Bargarh",
    "Paradip",
    "Angul",
    "Dhenkanal",
    "Balangir",
    "Kendujhar",
    "Rayagada",
    "Phulbani",
    "Koraput",
    "Sundargarh",
    "Nabarangpur",
    "Kendrapara",
    "Jagatsinghpur",
    "Ganjam",
    "Kalahandi",
    "Nuapada",
    "Malkangiri",
    "Subarnapur",
    "Boudh"
];

const punjabCities = [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Pathankot",
    "Hoshiarpur",
    "Batala",
    "Abohar",
    "Moga",
    "Khanna",
    "Maler Kotla",
    "Barnala",
    "Firozpur",
    "Phagwara",
    "Muktsar",
    "Rajpura",
    "Kapurthala",
    "Zirakpur",
    "Kot Kapura",
    "Faridkot",
    "Gurdaspur",
    "Fazilka",
    "Sangrur",
    "Mansa",
    "Sunam",
    "Tarn Taran",
    "Nabha",
    "Gobindgarh",
    "Mohali",
    "Malout",
    "Jagraon",
    "Rampura Phul",
    "Dhuri",
    "Longowal",
    "Patti",
    "Samana",
    "Nawanshahr",
    "Sirhind-Fategarh",
    "Sujanpur",
    "Pattran",
    "Talwara",
    "Puranpur",
    "Rupnagar",
    "Nangal",
    "Sunam",
    "Lehra",
    "Bhadaur",
    "Budhlada",
    "Cheema",
    "Dhanaula",
    "Dirba",
    "Handiaya",
    "Longowal",
    "Moonak",
    "Sangrur",
    "Ahmedgarh",
    "Amloh",
    "Bassi Pathana",
    "Fatehgarh Sahib",
    "Khamanon",
    "Mandi Gobindgarh",
    "Sirhind-Fategarh",
    "Faridkot",
    "Jaitu",
    "Kot Kapura",
    "Machhiwara",
    "Payal",
    "Raikot",
    "Sahnewal",
    "Samrala",
    "Talwara",
    "Urmar Tanda",
    "Zira"
];

const rajasthanCities = [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Tonk",
    "Beawar",
    "Ganganagar",
    "Hanumangarh",
    "Bundi",
    "Chittorgarh",
    "Jaisalmer",
    "Barmer",
    "Nagaur",
    "Dholpur",
    "Karauli",
    "Sawai Madhopur",
    "Jhalawar",
    "Jhunjhunu",
    "Banswara",
    "Dausa",
    "Baran",
    "Churu"
];

const sikkimCities = [
    "Gangtok",
    "Gyalshing",
    "Jorethang",
    "Mangan",
    "Namchi",
    "Nayabazar",
    "Rangpo",
    "Rhenak (Rhenock)",
    "Singtam",
    "Aritar"
];

const tamilNaduCities = [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tiruppur",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thoothukkudi",
    "Nagercoil",
    "Thanjavur",
    "Dindigul",
    "Cuddalore",
    "Kanchipuram",
    "Kumarapalayam",
    "Karur",
    "Udhagamandalam",
    "Hosūr",
    "Ambattur",
    "Avadi",
    "Tiruvottiyur",
    "Pallavaram",
    "Tambaram",
    "Sivakasi",
    "Karaikkudi",
    "Neyveli",
    "Nagapattinam",
    "Pudukkottai",
    "Vaniyambadi",
    "Ambur",
    "Rajapalayam",
    "Viluppuram",
    "Ramanathapuram",
    "Namakkal",
    "Kovilpatti",
    "Arakkonam",
    "Pollachi",
    "Gudiyatham",
    "Perambalur",
    "Arani",
    "Tindivanam",
    "Palani",
    "Pattukkottai",
    "Rameswaram",
    "Sirkazhi",
    "Tiruchengode",
    "Udumalaipettai",
    "Virudhunagar",
    "Theni Allinagaram",
    "Pudupalayam",
    "Periyakulam",
    "Valparai",
    "Manapparai",
    "P.N.Patti",
    "Thiruvarur",
    "Thiruvallur",
    "Panruti",
    "Vedaranyam",
    "Uthamapalayam",
    "Sankari",
    "Sivaganga",
    "Vikramasingapuram",
    "Thuraiyur",
    "Sathyamangalam",
    "Arakkonam",
    "Nellikuppam",
    "Palladam",
    "Pollachi",
    "Pudukkottai",
    "Rajapalayam",
    "Ramanathapuram",
    "Salem",
    "Sankarankoil",
    "Sathyamangalam",
    "Sivaganga",
    "Sivakasi",
    "Thanjavur",
    "Theni Allinagaram",
    "Thirumangalam",
    "Thirupuvanam",
    "Thiruthuraipoondi",
    "Thiruvallur",
    "Thiruvarur",
    "Thoothukkudi",
    "Tiruchendur",
    "Tiruchengode",
    "Tiruchirappalli",
    "Tirukalukundram",
    "Tirukkoyilur",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruttani",
    "Tiruvannamalai",
    "Tiruvethipuram",
    "Tittakudi",
    "Udhagamandalam",
    "Udumalaipettai",
    "Unnamalaikadai",
    "Usilampatti",
    "Uthamapalayam",
    "Uthiramerur",
    "Vadakkuvalliyur",
    "Vadalur",
    "Vadipatti",
    "Valparai",
    "Vandavasi",
    "Vaniyambadi",
    "Vedaranyam",
    "Vellakoil",
    "Vellore",
    "Vikramasingapuram",
    "Viluppuram",
    "Virudhachalam",
    "Virudhunagar",
    "Viswanatham"
];

const telanganaCities = [
    "Hyderabad",
    "Warangal",
    "Karimnagar",
    "Nizamabad",
    "Khammam",
    "Ramagundam",
    "Mahabubnagar",
    "Mancherial",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Miryalaguda",
    "Siddipet",
    "Jagtial",
    "Armoor",
    "Nirmal",
    "Sircilla",
    "Kamareddy",
    "Palwancha",
    "Kothagudem",
    "Bodhan",
    "Sangareddy",
    "Metpally",
    "Zahirabad",
    "Meerpet-Jillelguda",
    "Korutla",
    "Tandur",
    "Badangpet",
    "Kodad",
    "Utnoor",
    "Gadwal",
    "Wanaparthy",
    "Kagaznagar",
    "Bellampalle",
    "Khanapuram Haveli",
    "Bhuvanagiri",
    "Vikarabad",
    "Mahabubabad",
    "Jangaon",
    "Mandamarri",
    "Peerzadiguda",
    "Badepally",
    "Bhadrachalam",
    "Bandlaguda Jagir",
    "Kyathanpally",
    "Manuguru",
    "Naspur",
    "Narsampet",
    "Devarakonda",
    "Dubbaka",
    "Nakrekal",
    "Banswada",
    "Kalwakurthy",
    "Nagar Kurnool",
    "Parigi",
    "Thumkunta",
    "Neredcherla",
    "Luxettipet",
    "Aiza",
    "Nagaram",
    "Gajwel",
    "Chennur",
    "Asifabad",
    "Madhira",
    "Ghatkesar",
    "Kompally",
    "Dasnapur",
    "Sarapaka",
    "Husnabad",
    "Pocharam",
    "Dammaiguda",
    "Achampet",
    "Thorur",
    "Bhoothpur"
];

const tripuraCities = [
    "Agartala",
    "Dharmanagar",
    "Udaipur",
    "Kailashahar",
    "Bishalgarh",
    "Teliamura",
    "Khowai",
    "Belonia",
    "Melaghar",
    "Mohanpur",
    "Ambassa",
    "Ranirbazar",
    "Santirbazar",
    "Kumarghat",
    "Sonamura",
    "Panisagar",
    "Amarpur",
    "Jirania",
    "Kamalpur",
    "Sabroom"
];

const uttarPradeshCities = [
    "Kanpur",
    "Lucknow",
    "Ghaziabad",
    "Agra",
    "Meerut",
    "Varanasi",
    "Prayagraj",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Noida",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura",
    "Budaun",
    "Rampur",
    "Shahjahanpur",
    "Farrukhabad",
    "Ayodhya",
    "Mau",
    "Hapur",
    "Etawah",
    "Mirzapur",
    "Bulandshahr",
    "Sambhal",
    "Amroha",
    "Hardoi",
    "Pilibhit",
    "Barabanki",
    "Khurja",
    "Gonda",
    "Mainpuri",
    "Lalitpur",
    "Etah",
    "Deoria",
    "Ghazipur",
    "Sultanpur",
    "Azamgarh",
    "Fatehpur",
    "Raebareli",
    "Orai",
    "Sitapur",
    "Bahraich",
    "Modinagar",
    "Unnao",
    "Jaunpur",
    "Lakhimpur",
    "Hathras",
    "Banda"
];


const uttarakhandCities = [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani",
    "Rishikesh",
    "Kashipur",
    "Rudrapur",
    "Nainital",
    "Pithoragarh",
    "Ramnagar",
    "Manglaur",
    "Jaspur",
    "Kichha",
    "Almora",
    "Mussoorie",
    "Sitarganj",
    "Bajpur",
    "Pauri",
    "Tehri",
    "Gopeshwar",
    "Srinagar",
    "Gadarpur",
    "Tanakpur",
    "Uttarkashi",
    "Joshimath",
    "Khatima",
    "Vikasnagar",
    "Rudraprayag",
    "Bageshwar",
    "Bhowali",
    "Narendranagar",
    "Dugadda",
    "Raipur",
    "Dhandera",
    "Mukhani",
    "Nagla",
    "Umru Khurd",
    "Dhalwala",
    "Rawli Mahdud",
    "Central Hope Town",
    "Jagjitpur",
    "Mohanpur Mohammadpur",
    "Natthanpur",
    "Mehuwala Mafi",
    "Sunhaira",
    "Padali Gujjar",
    "Fatehpur Range",
    "Jivangarh",
    "Bandia",
    "Shafipur",
    "Maholia",
    "Kashirampur",
    "Salempur Rajputan",
    "Bahadrabad",
    "Piran Kaliyar",
    "Haripur Kalan",
    "Padampur Sukhron",
    "Pratitnagar",
    "Natthuwala",
    "Bangheri Mahabatpur",
    "Khadri Kharak Maf",
    "Haldwani Talli",
    "Banbasa",
    "Bhagwanpur",
    "Gumaniwala",
    "Khanjarpur",
    "Nagla Imarti",
    "Shahpur",
    "Saidpura",
    "Khatyari",
    "Jonk",
    "Kachnal Gosain",
    "Laksar",
    "Landhaura",
    "Mahua Kheraganj",
    "Dineshpur",
    "Jhabrera",
    "Kela Khera",
    "Muni Ki Reti",
    "Sultanpur",
    "Herbertpur",
    "Gauchar",
    "Doiwala",
    "Karnaprayag",
    "Lohaghat",
    "Chamba",
    "Bhimtal",
    "Lalkuan",
    "Kaladhungi",
    "Mahua Dabra Haripura",
    "Dharchula",
    "Barkot",
    "Didihat",
    "Shaktigarh",
    "Champawat",
    "Dwarahat",
    "Badrinath",
    "Devprayag",
    "Kirtinagar",
    "Nandaprayag",
    "Kedarnath",
    "Gangotri",
    "Garur",
    "Kapkot"
];


const westBengalCities = [
    "Kolkata",
    "Asansol",
    "Siliguri",
    "Durgapur",
    "Bardhaman",
    "English Bazar",
    "Baharampur",
    "Habra",
    "Kharagpur",
    "Shantipur",
    "Dankuni",
    "Dhulian",
    "Ranaghat",
    "Haldia",
    "Raiganj",
    "Krishnanagar",
    "Nabadwip",
    "Medinipur",
    "Jalpaiguri",
    "Balurghat",
    "Basirhat",
    "Bankura",
    "Chakdaha",
    "Darjeeling",
    "Alipurduar",
    "Purulia",
    "Jangipur",
    "Bangaon",
    "Cooch Behar"
];

const andamanAndNicobarPlaces = [
    "Port Blair",
    "Havelock Island",
    "Neil Island",
    "Baratang Island",
    "Ross Island",
    "North Bay Island",
    "Long Island",
    "Little Andaman",
    "Barren Island",
    "Diglipur",
    "Mayabunder",
    "Rangat",
    "Car Nicobar",
    "Katchal Island",
    "Great Nicobar"
];

const chandigarhAreas = [
    "Sector 1",
    "Sector 17",
    "Sector 22",
    "Sector 35",
    "Sector 43",
    "Manimajra",
    "Industrial Area Phase 1",
    "Industrial Area Phase 2",
    "Daria",
    "Burail",
    "Hallomajra",
    "Maloya",
    "Daddu Majra",
    "Kishangarh"
];

const dadraNagarHaveliDamanDiu = [
    // Dadra and Nagar Haveli
    "Silvassa",
    "Amli",
    "Dadra",
    "Naroli",
    "Samarvarni",
    "Rakholi",

    // Daman
    "Daman",
    "Moti Daman",
    "Nani Daman",
    "Varkund",
    "Kadaiya",

    // Diu
    "Diu",
    "Vanakbara",
    "Ghoghla",
    "Bucharwada",
    "Fudam"
]

const lakshadweepIslands = [
    "Kavaratti",
    "Agatti",
    "Bangaram",
    "Minicoy",
    "Amini",
    "Kadmat",
    "Kalpeni",
    "Chetlat",
    "Bitra",
    "Andrott"
];

const delhiDistricts = [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi"
]
const puducherryDistricts = [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam"
];
const jammuKashmirDistricts = [
    // Jammu Division
    "Jammu",
    "Samba",
    "Kathua",
    "Udhampur",
    "Reasi",
    "Ramban",
    "Doda",
    "Kishtwar",
    "Poonch",
    "Rajouri",

    // Kashmir Division
    "Srinagar",
    "Ganderbal",
    "Budgam",
    "Pulwama",
    "Anantnag",
    "Kulgam",
    "Shopian",
    "Baramulla",
    "Kupwara",
    "Bandipora"
];

const ladakhDistricts = [
    "Leh",
    "Kargil"
];



const states = [
    {
        name: "Madhya Pradesh",
        cities: madhyaPradesh
    },
    {
        name: "Andhra Pradesh",
        cities: andhraPradesh
    },
    {
        name: "Arunachal Pradesh",
        cities: arunachalPradesh
    },
    {
        name: "Assam",
        cities: assam
    },
    {
        name: "Bihar",
        cities: bihar
    }
    ,
    {
        name: "Chhattisgarh",
        cities: chhattisgarh
    },
    {
        name: "Goa",
        cities: goa
    },
    {
        name: "Gujarat",
        cities: gujarat
    },
    {
        name: "Haryana",
        cities: haryana
    },
    {
        name: "Himachal Pradesh",
        cities: himachalPradesh
    },
    {
        name: "Jharkhand",
        cities: jharkhand
    },
    {
        name: "Karnataka",
        cities: karnatakaCities
    },
    {
        name: "Kerala",
        cities: keralaCities
    },
    {
        name: "Maharashtra",
        cities: maharashtraCities
    },
    {
        name: "Manipur",
        cities: manipurCities
    },
    {
        name: "Meghalaya",
        cities: meghalayaCities
    },
    {
        name: "Mizoram",
        cities: mizoramCities
    },
    {
        name: "Nagaland",
        cities: nagalandCities
    },
    {
        name: "Odisha",
        cities: odishaCities
    },
    {
        name: "Punjab",
        cities: punjabCities
    },
    {
        name: "Rajasthan",
        cities: rajasthanCities
    },
    {
        name: "Sikkim",
        cities: sikkimCities
    },
    {
        name: "Tamil Nadu",
        cities: tamilNaduCities
    },
    {
        name: "Telangana",
        cities: telanganaCities
    },
    {
        name: "Tripura",
        cities: tripuraCities
    },
    {
        name: "Uttar Pradesh",
        cities: uttarPradeshCities
    },
    {
        name: "Uttarakhand",
        cities: uttarakhandCities
    },
    {
        name: "West Bengal",
        cities: westBengalCities
    },
    {
        name: "Andaman and Nicobar Islands",
        cities: andamanAndNicobarPlaces
    },
    {
        name: "Chandigarh",
        cities: chandigarhAreas
    },
    {
        name: "Dadra and Nagar Haveli and Daman and Diu",
        cities: dadraNagarHaveliDamanDiu
    },
    {
        name: "Lakshadweep",
        cities: lakshadweepIslands
    },
    {
        name: "Delhi",
        cities: delhiDistricts
    },
    {
        name: "Puducherry",
        cities: puducherryDistricts,
    },
    {
        name: "Jammu and Kashmir",
        cities: jammuKashmirDistricts
    },
    {
        name: "Ladakh",
        cities: ladakhDistricts
    }

]



export default states